const express = require("express");
const cors = require("cors");
const app = express();
app.use(cors());
const routes = require("./routes");
app.use(express.json());
// app.use(express.static(__dirname + "/dist"));
app.use(routes);
let port = 3000;
app.listen(port, _ => console.log(`Server running on port: ${port}`));
